 const categories = [
	'Arts & Photography',
	'Biographies & Memoirs',
	'Business & Money',
	'Calendars',
	"Children's Books",
	'Christian Books & Bibles',
	'Comics & Graphic Novels',
	'Computer & Technology',
	'Cookbooks, Food & Wine',
	'Crafts, Hobbies & Home',
	'Education & Teaching',
	'Engineering & Transportation',
	'Health, Fitness & Dieting',
	'History',
	'Humor & Entertainment',
	'Law',
	'Lesbian, Gay, Bisexual & Transgender Books',
	'Literature and Fiction',
	'Medical Books',
	'Mystery, Thriller & Suspense',
	'Parenting & Social Sciences',
	'Reference',
	'Religion & Spirituality',
	'Romance',
	'Science & Math',
	'Science Fiction & Fantasy',
	'Self-Help',
	'Sports & Outdoors',
	'Teen & Young Adult',
	'Test Preparation',
	'Travel',
	'Others',
];

export default categories;